# Array 的 input 和 output

## 使用 pickle 序列化 numpy array

In [2]:
import pickle
import numpy as np

In [4]:
# 创建 numpy Array
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# 使用 pickle 序列化
f = open('x.pki', 'wb') # 写二进制文件
pickle.dump(x, f)
# 查看当前目录的文件
!ls

Array的input和output.ipynb
NumPy中创建数组及访问数组的元素.ipynb
x.pki
数组和矩阵运算.ipynb


In [6]:
f = open('x.pki', 'rb') # 读二进制文件
pickle.load(f)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 使用 numpy 序列化 numpy array

In [7]:
np.save('one_array', x)
!ls

Array的input和output.ipynb
NumPy中创建数组及访问数组的元素.ipynb
one_array.npy
x.pki
数组和矩阵运算.ipynb


In [9]:
np.load('one_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# 同时序列化多个数组

In [11]:
y = np.arange(20)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [13]:
np.savez('two_array.npz', a=x, b=y)
!ls

Array的input和output.ipynb
NumPy中创建数组及访问数组的元素.ipynb
one_array.npy
two_array.npz
x.pki
数组和矩阵运算.ipynb


In [14]:
c = np.load('two_array.npz')

In [17]:
c['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
c['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])