# 数组和矩阵运算

In [1]:
import numpy as np

In [4]:
# 快速创建数组
# 创建一个随机元素的 10 位一维数组（元素符合正态分布）
np.random.randn(10) 

array([-0.17242745, -0.24089805,  1.7571844 , -0.0390764 , -1.67487818,
        1.22165836, -0.82615188,  0.08542429,  0.30850447,  1.89509861])

In [8]:
# 返回一个 10 以内的 int 型 随机数
np.random.randint(10) 

6

In [9]:
# 返回一个 10 以内的 int 型 2 乘 3 的二维数组
np.random.randint(10, size=(2, 3)) 

array([[2, 0, 4],
       [1, 1, 5]])

In [10]:
# 返回一个 10 以内的 int 型 20 位的一维数组
np.random.randint(10, size=20) 

array([2, 6, 7, 5, 8, 5, 5, 3, 2, 7, 1, 7, 3, 2, 1, 1, 0, 7, 6, 9])

In [11]:
# 将一个 10 以内的 int 型 20 位的一维数组，转换为一个 4 乘 5 的二维数组
np.random.randint(10, size=20).reshape(4, 5)

array([[6, 8, 1, 8, 5],
       [2, 4, 5, 7, 5],
       [3, 0, 4, 7, 4],
       [0, 4, 9, 4, 2]])

## 数组的运算

In [16]:
a = np.random.randint(10, size=20).reshape(4, 5)
a

array([[6, 5, 5, 8, 4],
       [8, 4, 6, 8, 1],
       [5, 7, 1, 5, 8],
       [0, 5, 4, 1, 2]])

In [17]:
b = np.random.randint(10, size=20).reshape(4, 5)
b

array([[3, 8, 8, 2, 6],
       [8, 1, 2, 5, 1],
       [4, 4, 3, 1, 7],
       [4, 8, 4, 1, 3]])

### 数组的加法

In [18]:
# 对应元素的和
a + b

array([[ 9, 13, 13, 10, 10],
       [16,  5,  8, 13,  2],
       [ 9, 11,  4,  6, 15],
       [ 4, 13,  8,  2,  5]])

### 属猪的减法

In [19]:
# 对应元素的差
a - b

array([[ 3, -3, -3,  6, -2],
       [ 0,  3,  4,  3,  0],
       [ 1,  3, -2,  4,  1],
       [-4, -3,  0,  0, -1]])

### 数组的乘法

In [20]:
# 对应元素的积
a * b

array([[18, 40, 40, 16, 24],
       [64,  4, 12, 40,  1],
       [20, 28,  3,  5, 56],
       [ 0, 40, 16,  1,  6]])

### 数组的除法

In [22]:
# 对应元素的商（当除数为 0 时，会有警告，结果以 inf 表示）
a / b

array([[2.        , 0.625     , 0.625     , 4.        , 0.66666667],
       [1.        , 4.        , 3.        , 1.6       , 1.        ],
       [1.25      , 1.75      , 0.33333333, 5.        , 1.14285714],
       [0.        , 0.625     , 1.        , 1.        , 0.66666667]])

In [24]:
# 创建矩阵
np.mat([[1, 2, 3], [4, 5, 6]])

matrix([[1, 2, 3],
        [4, 5, 6]])

In [25]:
# 将数组 a 转换成矩阵
np.mat(a)

matrix([[6, 5, 5, 8, 4],
        [8, 4, 6, 8, 1],
        [5, 7, 1, 5, 8],
        [0, 5, 4, 1, 2]])

## 矩阵的运算

In [28]:
A = np.mat(a)
A

matrix([[6, 5, 5, 8, 4],
        [8, 4, 6, 8, 1],
        [5, 7, 1, 5, 8],
        [0, 5, 4, 1, 2]])

In [29]:
B = np.mat(b)
B

matrix([[3, 8, 8, 2, 6],
        [8, 1, 2, 5, 1],
        [4, 4, 3, 1, 7],
        [4, 8, 4, 1, 3]])

### 矩阵的加法

In [30]:
# 矩阵的加法为对应元素的和
A + B

matrix([[ 9, 13, 13, 10, 10],
        [16,  5,  8, 13,  2],
        [ 9, 11,  4,  6, 15],
        [ 4, 13,  8,  2,  5]])

### 矩阵的减法

In [32]:
# 矩阵的减法为对应元素的差
A - B

matrix([[ 3, -3, -3,  6, -2],
        [ 0,  3,  4,  3,  0],
        [ 1,  3, -2,  4,  1],
        [-4, -3,  0,  0, -1]])

### 矩阵的乘法

In [33]:
# 会报错
A * B

ValueError: shapes (4,5) and (4,5) not aligned: 5 (dim 1) != 4 (dim 0)

In [34]:
A = np.mat(np.random.randint(10, size=20).reshape(4, 5))
A

matrix([[9, 0, 3, 8, 6],
        [4, 0, 7, 1, 8],
        [4, 7, 2, 2, 7],
        [2, 4, 2, 1, 5]])

In [35]:
B = np.mat(np.random.randint(10, size=20).reshape(5, 4))
B

matrix([[2, 0, 7, 0],
        [4, 7, 3, 6],
        [9, 9, 0, 9],
        [7, 4, 9, 3],
        [2, 1, 4, 4]])

In [37]:
# 4 乘 5 的矩阵与 5 乘 4 的矩阵的积为一个 4 乘 4 的矩阵 
A * B

matrix([[113,  65, 159,  75],
        [ 94,  75,  69,  98],
        [ 82,  82,  95,  94],
        [ 55,  55,  55,  65]])

## Array 的常用函数

In [39]:
c = np.random.randint(10, size=20).reshape(4, 5)
c

array([[1, 2, 2, 6, 8],
       [0, 4, 4, 6, 8],
       [7, 8, 1, 0, 8],
       [7, 2, 4, 0, 5]])

In [40]:
# 返回 c 中 唯一的（不重复）的值
np.unique(c)

array([0, 1, 2, 4, 5, 6, 7, 8])

In [43]:
# 求和，多维数组所有列的和
sum(c)

array([15, 16, 11, 12, 29])

In [42]:
# 求和，多维数组第 0 行的和
sum(c[0])

19

In [46]:
# 求和，多维数组第 0 列的和
sum(c[:, 0])

15

In [47]:
# 数组中的最大值，求m
c.max()

8